// Mocks generated by Mockito 5.4.6 from annotations
// in stash_app_flutter/test/activity_tracking_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i12;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:stash_app_flutter/core/domain/entities/scraped/scraped_scene.dart'
    as _i8;
import 'package:stash_app_flutter/features/scenes/domain/entities/scene.dart'
    as _i2;
import 'package:stash_app_flutter/features/scenes/domain/entities/scene_filter.dart'
    as _i6;
import 'package:stash_app_flutter/features/scenes/domain/models/scraper.dart'
    as _i7;
import 'package:stash_app_flutter/features/scenes/domain/repositories/scene_repository.dart'
    as _i4;
import 'package:video_player/src/closed_caption_file.dart' as _i11;
import 'package:video_player/video_player.dart' as _i3;
import 'package:video_player_platform_interface/video_player_platform_interface.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeScene_0 extends _i1.SmartFake implements _i2.Scene {
  _FakeScene_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVideoPlayerValue_1 extends _i1.SmartFake
    implements _i3.VideoPlayerValue {
  _FakeVideoPlayerValue_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SceneRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSceneRepository extends _i1.Mock implements _i4.SceneRepository {
  MockSceneRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Scene>> findScenes({
    int? page,
    int? perPage,
    String? filter,
    String? sort,
    bool? descending = true,
    bool? organized,
    bool? performerFavorite,
    String? performerId,
    String? studioId,
    String? tagId,
    _i6.SceneFilter? sceneFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findScenes, [], {
              #page: page,
              #perPage: perPage,
              #filter: filter,
              #sort: sort,
              #descending: descending,
              #organized: organized,
              #performerFavorite: performerFavorite,
              #performerId: performerId,
              #studioId: studioId,
              #tagId: tagId,
              #sceneFilter: sceneFilter,
            }),
            returnValue: _i5.Future<List<_i2.Scene>>.value(<_i2.Scene>[]),
          )
          as _i5.Future<List<_i2.Scene>>);

  @override
  _i5.Future<_i2.Scene> getSceneById(String? id, {bool? refresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getSceneById, [id], {#refresh: refresh}),
            returnValue: _i5.Future<_i2.Scene>.value(
              _FakeScene_0(
                this,
                Invocation.method(#getSceneById, [id], {#refresh: refresh}),
              ),
            ),
          )
          as _i5.Future<_i2.Scene>);

  @override
  _i5.Future<List<_i7.Scraper>> listScrapers({required List<String>? types}) =>
      (super.noSuchMethod(
            Invocation.method(#listScrapers, [], {#types: types}),
            returnValue: _i5.Future<List<_i7.Scraper>>.value(<_i7.Scraper>[]),
          )
          as _i5.Future<List<_i7.Scraper>>);

  @override
  _i5.Future<List<_i8.ScrapedScene>> scrapeSingleScene({
    String? scraperId,
    String? stashBoxEndpoint,
    String? sceneId,
    String? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scrapeSingleScene, [], {
              #scraperId: scraperId,
              #stashBoxEndpoint: stashBoxEndpoint,
              #sceneId: sceneId,
              #query: query,
            }),
            returnValue: _i5.Future<List<_i8.ScrapedScene>>.value(
              <_i8.ScrapedScene>[],
            ),
          )
          as _i5.Future<List<_i8.ScrapedScene>>);

  @override
  _i5.Future<_i8.ScrapedScene?> scrapeSceneURL(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#scrapeSceneURL, [url]),
            returnValue: _i5.Future<_i8.ScrapedScene?>.value(),
          )
          as _i5.Future<_i8.ScrapedScene?>);

  @override
  _i5.Future<void> generatePhash(String? sceneId) =>
      (super.noSuchMethod(
            Invocation.method(#generatePhash, [sceneId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveScrapedScene({
    required String? sceneId,
    required _i8.ScrapedScene? scraped,
    bool? mergeValues = false,
    List<String>? performerIds,
    List<String>? tagIds,
    String? studioId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveScrapedScene, [], {
              #sceneId: sceneId,
              #scraped: scraped,
              #mergeValues: mergeValues,
              #performerIds: performerIds,
              #tagIds: tagIds,
              #studioId: studioId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, List<Map<String, dynamic>>>> findPerformerCandidates(
    List<String>? queries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findPerformerCandidates, [queries]),
            returnValue:
                _i5.Future<Map<String, List<Map<String, dynamic>>>>.value(
                  <String, List<Map<String, dynamic>>>{},
                ),
          )
          as _i5.Future<Map<String, List<Map<String, dynamic>>>>);

  @override
  _i5.Future<Map<String, List<Map<String, dynamic>>>> findTagCandidates(
    List<String>? tags,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findTagCandidates, [tags]),
            returnValue:
                _i5.Future<Map<String, List<Map<String, dynamic>>>>.value(
                  <String, List<Map<String, dynamic>>>{},
                ),
          )
          as _i5.Future<Map<String, List<Map<String, dynamic>>>>);

  @override
  _i5.Future<void> updateSceneRating(String? id, int? rating100) =>
      (super.noSuchMethod(
            Invocation.method(#updateSceneRating, [id, rating100]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> incrementSceneOCounter(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#incrementSceneOCounter, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> incrementScenePlayCount(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#incrementScenePlayCount, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveSceneActivity(
    String? id, {
    double? resumeTime,
    double? playDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveSceneActivity,
              [id],
              {#resumeTime: resumeTime, #playDuration: playDuration},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [VideoPlayerController].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoPlayerController extends _i1.Mock
    implements _i3.VideoPlayerController {
  MockVideoPlayerController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get dataSource =>
      (super.noSuchMethod(
            Invocation.getter(#dataSource),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#dataSource),
            ),
          )
          as String);

  @override
  Map<String, String> get httpHeaders =>
      (super.noSuchMethod(
            Invocation.getter(#httpHeaders),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i10.DataSourceType get dataSourceType =>
      (super.noSuchMethod(
            Invocation.getter(#dataSourceType),
            returnValue: _i10.DataSourceType.asset,
          )
          as _i10.DataSourceType);

  @override
  _i10.VideoViewType get viewType =>
      (super.noSuchMethod(
            Invocation.getter(#viewType),
            returnValue: _i10.VideoViewType.textureView,
          )
          as _i10.VideoViewType);

  @override
  int get playerId =>
      (super.noSuchMethod(Invocation.getter(#playerId), returnValue: 0) as int);

  @override
  _i5.Future<Duration?> get position =>
      (super.noSuchMethod(
            Invocation.getter(#position),
            returnValue: _i5.Future<Duration?>.value(),
          )
          as _i5.Future<Duration?>);

  @override
  _i3.VideoPlayerValue get value =>
      (super.noSuchMethod(
            Invocation.getter(#value),
            returnValue: _FakeVideoPlayerValue_1(
              this,
              Invocation.getter(#value),
            ),
          )
          as _i3.VideoPlayerValue);

  @override
  set value(_i3.VideoPlayerValue? newValue) => super.noSuchMethod(
    Invocation.setter(#value, newValue),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> play() =>
      (super.noSuchMethod(
            Invocation.method(#play, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setLooping(bool? looping) =>
      (super.noSuchMethod(
            Invocation.method(#setLooping, [looping]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> seekTo(Duration? position) =>
      (super.noSuchMethod(
            Invocation.method(#seekTo, [position]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setPlaybackSpeed(double? speed) =>
      (super.noSuchMethod(
            Invocation.method(#setPlaybackSpeed, [speed]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void setCaptionOffset(Duration? offset) => super.noSuchMethod(
    Invocation.method(#setCaptionOffset, [offset]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> setClosedCaptionFile(
    _i5.Future<_i11.ClosedCaptionFile>? closedCaptionFile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setClosedCaptionFile, [closedCaptionFile]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i3.VideoAudioTrack>> getAudioTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getAudioTracks, []),
            returnValue: _i5.Future<List<_i3.VideoAudioTrack>>.value(
              <_i3.VideoAudioTrack>[],
            ),
          )
          as _i5.Future<List<_i3.VideoAudioTrack>>);

  @override
  _i5.Future<void> selectAudioTrack(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#selectAudioTrack, [trackId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isAudioTrackSupportAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isAudioTrackSupportAvailable, []),
            returnValue: false,
          )
          as bool);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
