targets:
  $default:
    builders:
      mockito|mock_builder:
        enabled: true
        generate_for:
          - test/**
      riverpod_generator:
        enabled: true
      freezed:
        enabled: true
      json_serializable:
        enabled: true
      graphql_codegen:
        options:
          clients:
            - graphql
          schema_mapping:
            - schema: graphql/combined_schema.graphql
              queries_glob: lib/features/**/*.graphql
              output_directory: lib/core/data/graphql/__generated__
